services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fabri005
      POSTGRES_DB: pichangapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pichanga_net

  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - pichanga_net

volumes:
  pgdata:
  mongodata:

networks:
  pichanga_net:
    external: true
    name: pichanga_net
